<a href="https://colab.research.google.com/github/HyperNBC/Proyecto_Integrador/blob/Dataset/PROYECTO_CAMBIO_CLIM%C3%81TICO_SISTEMAS_AGROALIMENTARIOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ANALISIS DE DATOS /PROYECTO ANÁLISIS DE DATOS/Emissions_Totals_E_All_Data_(Normalized).csv")

**ANÁLISIS EXPLORATORIO DE DATOS (EDA)**

In [ ]:
df

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Year Code,Year,Source Code,Source,Unit,Value,Flag,Note
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1961,1961,3050,FAO TIER 1,kt,8.762000e-01,E,NaN
1,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1962,1962,3050,FAO TIER 1,kt,8.829000e-01,E,NaN
2,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1963,1963,3050,FAO TIER 1,kt,8.236000e-01,E,NaN
3,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1964,1964,3050,FAO TIER 1,kt,8.882000e-01,E,NaN
4,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1965,1965,3050,FAO TIER 1,kt,8.978000e-01,E,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397455,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2018,2018,3050,FAO TIER 1,kt,1.555672e+07,E,NaN
2397456,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2019,2019,3050,FAO TIER 1,kt,1.524222e+07,E,NaN
2397457,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2020,2020,3050,FAO TIER 1,kt,1.411602e+07,E,NaN
2397458,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2021,2021,3050,FAO TIER 1,kt,1.476306e+07,E,NaN
2397459,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2022,2022,3050,FAO TIER 1,kt,1.478445e+07,E,NaN

In [ ]:
df.describe()

,Area Code,Item Code,Element Code,Year Code,Year,Source Code,Value,Note
count,2.397460e+06,2.397460e+06,2.397460e+06,2.397460e+06,2.397460e+06,2.397460e+06,2.397460e+06,0.0
mean,9.456798e+02,8.087478e+03,3.561720e+05,2.000950e+03,2.000950e+03,3.050036e+03,3.580586e+04,NaN
std,1.915836e+03,1.216180e+04,3.580428e+05,1.546891e+01,1.546891e+01,1.861326e-01,5.322502e+05,NaN
min,1.000000e+00,1.707000e+03,7.225000e+03,1.961000e+03,1.961000e+03,3.050000e+03,-1.249870e+07,NaN
25%,7.900000e+01,5.063000e+03,7.230000e+03,1.993000e+03,1.993000e+03,3.050000e+03,1.567000e-01,NaN
50%,1.500000e+02,6.517000e+03,7.273000e+03,2.003000e+03,2.003000e+03,3.050000e+03,1.516830e+01,NaN
75%,2.240000e+02,6.825000e+03,7.243130e+05,2.013000e+03,2.013000e+03,3.050000e+03,8.138455e+02,NaN
max,5.873000e+03,6.992100e+04,7.244130e+05,2.050000e+03,2.050000e+03,3.051000e+03,5.351073e+07,NaN

In [ ]:
df.head() # Muestra las primeras filas de la base de datos

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Year Code,Year,Source Code,Source,Unit,Value,Flag,Note
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1961,1961,3050,FAO TIER 1,kt,0.8762,E,NaN
1,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1962,1962,3050,FAO TIER 1,kt,0.8829,E,NaN
2,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1963,1963,3050,FAO TIER 1,kt,0.8236,E,NaN
3,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1964,1964,3050,FAO TIER 1,kt,0.8882,E,NaN
4,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1965,1965,3050,FAO TIER 1,kt,0.8978,E,NaN

In [ ]:
df.tail() # Muestra los últimos 5 registros

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Year Code,Year,Source Code,Source,Unit,Value,Flag,Note
2397455,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2018,2018,3050,FAO TIER 1,kt,1.555672e+07,E,NaN
2397456,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2019,2019,3050,FAO TIER 1,kt,1.524222e+07,E,NaN
2397457,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2020,2020,3050,FAO TIER 1,kt,1.411602e+07,E,NaN
2397458,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2021,2021,3050,FAO TIER 1,kt,1.476306e+07,E,NaN
2397459,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2022,2022,3050,FAO TIER 1,kt,1.478445e+07,E,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2397460 entries, 0 to 2397459
Data columns (total 15 columns):
 #   Column           Dtype
---  ------           -----
 0   Area Code        int64
 1   Area Code (M49)  object
 2   Area             object
 3   Item Code        int64
 4   Item             object
 5   Element Code     int64
 6   Element          object
 7   Year Code        int64
 8   Year             int64
 9   Source Code      int64
 10  Source           object
 11  Unit             object
 12  Value            float64
 13  Flag             object
 14  Note             float64
dtypes: float64(2), int64(6), object(7)
memory usage: 274.4+ MB

In [ ]:
df.columns

Index(['Area Code', 'Area Code (M49)', 'Area', 'Item Code', 'Item',
       'Element Code', 'Element', 'Year Code', 'Year', 'Source Code', 'Source',
       'Unit', 'Value', 'Flag', 'Note'],
      dtype='object')

In [ ]:
df.isnull()  # Identificar valores nulos (Son aquellos donde se muestra True)

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Year Code,Year,Source Code,Source,Unit,Value,Flag,Note
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397455,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2397456,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2397457,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2397458,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2397459,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [ ]:
pd.unique(df["Area Code"])

array([   2,    3,    4,    5,    6,    7,  258,    8,    9,    1,   22,
         10,   11,   52,   12,   13,   16,   14,   57,  255,   15,   23,
         53,   17,   18,   19,   80,   20,   21,  239,   26,   27,  233,
         29,   35,  115,   32,   33,   36,   37,   39,  259,   40,  351,
         96,  128,   41,  214,   44,   45,   46,   47,   48,  107,   98,
         49,   50,  167,   51,  116,  250,   54,   72,   55,   56,   58,
         59,   60,   61,  178,   63,  209,  238,   62,   65,   64,   66,
         67,   68,   69,   70,   74,   75,   73,   79,   81,   82,   84,
         85,   86,   87,   88,   89,   90,  175,   91,   93,   94,   95,
         97,   99,  100,  101,  102,  103,  104,  264,  105,  106,  109,
        110,  112,  108,  114,   83,  118,  113,  120,  119,  121,  122,
        123,  124,  125,  126,  256,  129,  130,  131,  132,  133,  134,
        127,  135,  136,  137,  270,  138,  145,  140,  141,  273,  142,
        143,  144,   28,  147,  148,  149,  150,  151,  153,  156,  157,
        158,  159,  160,  161,  154,  163,  162,  221,  164,  165,  180,
        299,  166,  168,  169,  170,  171,  172,  173,  174,  177,  179,
        117,  146,  182,  183,  185,  184,  187,  188,  189,  190,  191,
        244,  192,  193,  194,  195,  272,  186,  196,  197,  200,  199,
        198,   25,  201,  202,  277,  203,   38,  276,  206,  207,  260,
        210,  211,  212,  208,  216,  176,  217,  218,  219,  220,  222,
        223,  213,  224,  227,  226,  230,  225,  229,  215,  231,  240,
        234,  228,  235,  155,  236,  237,  243,  205,  249,  248,  251,
        181, 5000, 5100, 5101, 5102, 5103, 5104, 5105, 5200, 5203, 5204,
       5206, 5207, 5300, 5301, 5302, 5303, 5304, 5305, 5400, 5401, 5402,
       5403, 5404, 5500, 5501, 5502, 5503, 5504, 5707, 5801, 5802, 5803,
       5815, 5817, 5848, 5849, 5873])

In [ ]:
"""
NORMA M49: Códigos normalizados de país o área para uso estadístico

Link de consulta: https://unstats.un.org/unsd/methodology/m49/
"""

pd.unique(df["Area Code (M49)"])

array(["'004", "'008", "'012", "'016", "'020", "'024", "'660", "'028",
       "'032", "'051", "'533", "'036", "'040", "'031", "'044", "'048",
       "'050", "'052", "'112", "'056", "'058", "'084", "'204", "'060",
       "'064", "'068", "'070", "'072", "'076", "'092", "'096", "'100",
       "'854", "'108", "'132", "'116", "'120", "'124", "'136", "'140",
       "'148", "'830", "'152", "'159", "'344", "'446", "'156", "'158",
       "'170", "'174", "'178", "'184", "'188", "'384", "'191", "'192",
       "'196", "'203", "'200", "'408", "'180", "'208", "'262", "'212",
       "'214", "'218", "'818", "'222", "'226", "'232", "'233", "'748",
       "'231", "'230", "'238", "'234", "'242", "'246", "'250", "'254",
       "'258", "'266", "'270", "'268", "'276", "'288", "'292", "'300",
       "'304", "'308", "'312", "'316", "'320", "'324", "'624", "'328",
       "'332", "'336", "'340", "'348", "'352", "'356", "'360", "'364",
       "'368", "'372", "'833", "'376", "'380", "'388", "'392", "'400",
       "'398", "'404", "'296", "'414", "'417", "'418", "'428", "'422",
       "'426", "'430", "'434", "'438", "'440", "'442", "'450", "'454",
       "'458", "'462", "'466", "'470", "'584", "'474", "'478", "'480",
       "'175", "'484", "'583", "'492", "'496", "'499", "'500", "'504",
       "'508", "'104", "'516", "'520", "'524", "'528", "'530", "'540",
       "'554", "'558", "'562", "'566", "'570", "'574", "'807", "'580",
       "'578", "'512", "'582", "'586", "'585", "'275", "'591", "'598",
       "'600", "'604", "'608", "'612", "'616", "'620", "'630", "'634",
       "'410", "'498", "'638", "'642", "'643", "'646", "'654", "'659",
       "'662", "'666", "'670", "'882", "'674", "'678", "'682", "'686",
       "'688", "'891", "'690", "'694", "'702", "'703", "'705", "'090",
       "'706", "'710", "'728", "'724", "'144", "'729", "'736", "'740",
       "'744", "'752", "'756", "'760", "'762", "'764", "'626", "'768",
       "'772", "'776", "'780", "'788", "'792", "'795", "'796", "'798",
       "'800", "'804", "'784", "'826", "'834", "'840", "'850", "'858",
       "'810", "'860", "'548", "'862", "'704", "'876", "'732", "'887",
       "'890", "'894", "'716", "'001", "'002", "'014", "'017", "'015",
       "'018", "'011", "'019", "'021", "'013", "'029", "'005", "'142",
       "'143", "'030", "'034", "'035", "'145", "'150", "'151", "'154",
       "'039", "'155", "'009", "'053", "'054", "'057", "'061", "'097",
       "'199", "'432", "'722", "'901", "'902", "'907", "'908", "'198"],
      dtype=object)

In [ ]:
# Organización para la Cooperación y el Desarrollo Económico (OCDE)

pd.unique(df["Area"])

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belgium-Luxembourg', 'Belize', 'Benin', 'Bermuda',
       'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Channel Islands', 'Chile', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, mainland', 'China, Taiwan Province of',
       'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica',
       "Côte d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       'Czechoslovakia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR',
       'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Guiana', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (Federated States of)', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands (Kingdom of the)', 'Netherlands Antilles (former)',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'Norfolk Island', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Oman',
       'Pacific Islands Trust Territory', 'Pakistan', 'Palau',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico',
       'Qatar', 'Republic of Korea', 'Republic of Moldova', 'Réunion',
       'Romania', 'Russian Federation', 'Rwanda',
       'Saint Helena, Ascension and Tristan da Cunha',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Serbia and Montenegro', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sudan (former)', 'Suriname',
       'Svalbard and Jan Mayen Islands', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste',
       'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Türkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
       'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'United States Virgin Islands', 'Uruguay', 'USSR', 'Uzbekistan',
       'Vanuatu', 'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Western Sahara', 'Yemen',
       'Yugoslav SFR', 'Zambia', 'Zimbabwe', 'World', 'Africa',
       'Eastern Africa', 'Middle Africa', 'Northern Africa',
       'Southern Africa', 'Western Africa', 'Americas',
       'Northern America', 'Central America', 'Caribbean',
       'South America', 'Asia', 'Central Asia', 'Eastern Asia',
       'Southern Asia', 'South-eastern Asia', 'Western Asia', 'Europe',
       'Eastern Europe', 'Northern Europe', 'Southern Europe',
       'Western Europe', 'Oceania', 'Australia and New Zealand',
       'Melanesia', 'Micronesia', 'Polynesia', 'European Union (27)',
       'Least Developed Countries', 'Land Locked Developing Countries',
       'Small Island Developing States',
       'Low Income Food Deficit Countries',
       'Net Food Importing Developing Countries', 'Annex I countries',
       'Non-Annex I countries', 'OECD'], dtype=object)

In [ ]:
pd.unique(df["Item Code"])

array([ 5064,  5060,  5066,  5058,  5059,  5063,  5062,  5061,  6729,
       67292, 67291,  6994,  6751,  6750,  6795,  6993,  6992, 69921,
        6991,  6504,  6508,  6505,  6815,  6821,  6817,  6818,  6819,
        6518,  6996,  6516,  6517,  6995,  5084,  5085,  1711,  1709,
        1707,  6824,  6825,  6829,  6997,  6507,  6506,  6820])

In [ ]:
df

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Year Code,Year,Source Code,Source,Unit,Value,Flag,Note
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1961,1961,3050,FAO TIER 1,kt,8.762000e-01,E,NaN
1,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1962,1962,3050,FAO TIER 1,kt,8.829000e-01,E,NaN
2,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1963,1963,3050,FAO TIER 1,kt,8.236000e-01,E,NaN
3,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1964,1964,3050,FAO TIER 1,kt,8.882000e-01,E,NaN
4,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),1965,1965,3050,FAO TIER 1,kt,8.978000e-01,E,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397455,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2018,2018,3050,FAO TIER 1,kt,1.555672e+07,E,NaN
2397456,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2019,2019,3050,FAO TIER 1,kt,1.524222e+07,E,NaN
2397457,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2020,2020,3050,FAO TIER 1,kt,1.411602e+07,E,NaN
2397458,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2021,2021,3050,FAO TIER 1,kt,1.476306e+07,E,NaN
2397459,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),2022,2022,3050,FAO TIER 1,kt,1.478445e+07,E,NaN